#!/usr/bin/env bash

stack=${1:-example}
env=${2:-staging}
group=${3:-"$env"}
stacks="$(find services/* -maxdepth 1 -type d | awk -F/ '{print $NF}')"

prepare_stack () {
    source <(find "services/$stack" -type f -name '.env' -exec sed -E -n 's/[^#]+/export &/ p' {} +)

    service=".*\\/$stack"
    conf="\\.$env"
    child=".*"
    regex="$service\\/\\($child\\)?docker-compose\\($conf\\)?\\.yml$"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        cmd="find -E services/ -regex $regex"
    else
        cmd="find services/ -regextype posix-extended -regex $regex"
    fi

    files=$(sh -c "$cmd | xargs -n 1 -I \"%\" echo '-f' \"%\" | tr '\\n' ' '")

    # WARNING: Don't quote $files

    docker-compose $files config > docker-compose.yml
}

sync_stack () {
    git="$(find "services/$stack" -name '.git*')"
    if [ -n "$git" ]; then
        git submodule update --init --remote --merge "services/$stack"
    fi
}

cleanup () {
    rm -f docker-compose.yml
}

build () {
    sync_stack
    prepare_stack

    time ansible-playbook ansible/playbooks/build.yml -i "ansible/environments/$env" \
         -e "{\"project_path\": \"$(pwd)\", \"env\": \"$env\", \"group\": \"$group\", \"stack\": \"$stack\"}"

    status_code="$?"
    [ "$status_code" != 0 ] && exit 1

    cleanup
}

help () {
    echo "Usage: $0"
    echo 'Default: *'
    echo 'Stacks: *example'
    echo ''
    echo "$stacks"
    echo ''
    echo 'Environments: *staging'
    exit 1
}

if [ ! -d "services/$stack" ]; then
    help
fi

# WARNING: Don't delete quotes $stacks

for i in "$stacks"; do
    case "$i" in
        *$stack*)
            case "$env" in
                'staging'|'test')
                    build
                    ;;
                *)
                    help
                    ;;
            esac
            ;;
        *)
            help
            ;;
    esac
done
