#!/usr/bin/env bash

stack=${1:-example}
env=${2:-staging}
group=${3:-"$env"}
stacks="$(find services/* -maxdepth 1 -type d | awk -F/ '{print $NF}')"

prepare_stack () {
    source <(find "services/$stack" -type f -name '.env' -exec sed -E -n 's/[^#]+/export &/ p' {} +)

    service=".*\\/$stack"
    conf="\\.swarm\\|\\.$env"
    child=".*"
    regex="$service\\/\\($child\\)?docker-compose\\($conf\\)?\\.yml$"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        cmd="find -E services/ -type f -regex $regex"
    else
        cmd="find services/ -type f -regextype posix-extended -regex $regex"
    fi

    files=$(sh -c "$cmd | xargs -n 1 -I \"%\" echo '-f' \"%\" | tr '\\n' ' '")

    # WARNING: don't quote $files

    docker-compose $files config > docker-compose.yml
}

sync_stack () {
    git="$(find "services/$stack" -name '.git*')"
    if [ -n "$git" ]; then
        git submodule update --init --remote --merge "services/$stack"
    fi
}

deploy () {
    sync_stack
    prepare_stack

    date=$(date '+%Y-%m-%d %H:%M:%S')

    time ansible-playbook ansible/playbooks/deploy.yml -i "ansible/environments/$env" \
         -e "{\"date\": \"$date\", \"group\": \"$group\", \"env\": \"$env\", \"stack\": \"$stack\"}"
}

help () {
    echo "Usage: $0"
    echo 'Default: *'
    echo 'Stacks: *example'
    echo ''
    echo "$stacks"
    echo ''
    echo 'Environments: *staging'
    exit 1
}

if [ ! -d "services/$stack" ]; then
    help
fi

echo -e "\nRUN [Deploy \"$stack\" stack & \"$env\" env to \"$group\" server(s) ...]\n"

# WARNING: don't delete quotes $stacks

for i in "$stacks"; do
    case "$i" in
        *$stack*)
            case "$env" in
                'staging'|'test')
                    deploy
                    ;;
                *)
                    help
                    ;;
            esac
            ;;
        *)
            help
            ;;
    esac
done
